import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Polygon;
import java.awt.geom.GeneralPath;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

public class Kapal extends javax.swing.JFrame {

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
   
        Graphics2D g2 = (Graphics2D)g;
        g2.setColor(Color.BLUE);
       
        g2.translate(50, 50);
        Polygon kapal = new Polygon();
        kapal.addPoint(30, 100);
        kapal.addPoint(100, 100);
        kapal.addPoint(100, 90);
        kapal.addPoint(125, 90);
        kapal.addPoint(125, 60);
        kapal.addPoint(130, 60);
        kapal.addPoint(140, 70);
        kapal.addPoint(130, 75);
        kapal.addPoint(130, 90);
        kapal.addPoint(155, 90);
        kapal.addPoint(155, 100);
        kapal.addPoint(225, 100);
        kapal.addPoint(200, 125);
        kapal.addPoint(55, 125);
        kapal.addPoint(30, 100);
        g2.fill(kapal);
        g2.draw(kapal);
       
       
        //Membuat Bintang
        GeneralPath p = new GeneralPath(GeneralPath.WIND_NON_ZERO);
        p.moveTo(- 100.0f, -25.0f);
        p.lineTo(+ 100.0f, - 25.0f);
        p.lineTo(- 50.0f, + 100.0f);
        p.lineTo(+ 0.0f, - 100.0f);
        p.lineTo(+ 50.0f, + 100.0f);
        p.closePath();
       
        g2.translate(250.0f, 160.0f);
        g2.setColor(Color.red);
        g2.draw(p);
       
       
        GeneralPath gp = new GeneralPath();
        gp.moveTo(60, 120);
        gp.lineTo(80, 120);
       
        gp.lineTo(80, 120);
       
        gp.lineTo(80, 120);
       
        gp.lineTo(80, 120);
        gp.lineTo(80, 120);
        gp.lineTo(80, 120);
        gp.lineTo(80, 120);
       
    }
   
   

    /**
     * Creates new form Kapal
     */
    public Kapal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                         
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kapal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                    
    // End of variables declaration                  
}